### ISSUE TITLE
Text encoding issue?

### ISSUE THREAD

**Issue by czarathustra** [vishnevskiy/battlenet#7]
Throws error when attempting to decode inputs of non-standard english characters. For instance, test_unicode () in test_character.py results in:
## ERROR: test_unicode (**main**.CharacterTest)

Traceback (most recent call last):
  File "C:\Users\Isaac\Desktop\test_character.py", line 87, in test_unicode
    character = Character(battlenet.UNITED_STATES, 'Nazjatar', 'ClÃ­')
  File "D:\Python27\lib\battlenet\things.py", line 135, in **init**
    data = self.connection.get_character(region, realm, name, raw=True, fields=self._fields)
  File "D:\Python27\lib\battlenet\connection.py", line 114, in get_character
    name = quote(name.lower())
  File "D:\Python27\lib\battlenet\utils.py", line 13, in quote
    return urllib.quote(normalize(name))
  File "D:\Python27\lib\battlenet\utils.py", line 7, in normalize
    name = name.decode('utf8')
  File "D:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 2-3: unexpected end of data

---

I ran this test after the following resulted in a similar error:

```
import battlenet
from battlenet import Connection, Character
character = Character(battlenet.UNITED_STATES,'Stormreaver','Tøth',fields=[Character.ITEMS]) 
```

ø is  character 248 in Latin1. Resulting error reads:

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    character = Character(battlenet.UNITED_STATES,'Stormreaver','Tøth',fields=[Character.ITEMS])
  File "D:\Python27\lib\battlenet\things.py", line 135, in **init**
    data = self.connection.get_character(region, realm, name, raw=True, fields=self._fields)
  File "D:\Python27\lib\battlenet\connection.py", line 114, in get_character
    name = quote(name.lower())
  File "D:\Python27\lib\battlenet\utils.py", line 13, in quote
    return urllib.quote(normalize(name))
  File "D:\Python27\lib\battlenet\utils.py", line 7, in normalize
    name = name.decode('utf8')
  File "D:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf8 in position 1: invalid start byte

---

Possible user error? I ran the test to be sure. Running Python 2.7 on Windows.

**Comment by vishnevskiy** [comment]
These tests are definitely passing fine on my machine.

I also tested the following code and it worked fine.

```
# -*- coding: utf-8 -*-
import battlenet
from battlenet import Character
character = Character(battlenet.UNITED_STATES,'Stormreaver','Tøth',fields=[Character.ITEMS]) 
print character.name
```

**Comment by czarathustra** [comment]
99% sure this is some kind of user error. test_character.py is correct when I open it in IDLE, but not in Notepad (accented i in Cli appears as Ã).  Something's going horribly wrong between the text interpreter and the actual command line...

**Comment by vishnevskiy** [comment]
I don't suggest working in Notepad.

Notepad++ would be a better choice if you want a simple editor.

**Comment by czarathustra** [comment]
Verbatim, your example code isn't working.  Hex editor seems to show the characters are encoded correctly.  I must have inadvertently changed the text encoding on my machine when doing some file I/O in Perl. Looking into the problem.

**Comment by czarathustra** [comment]
Yea I've tried using Notepad++. Copied and pasted the code into it and ensure it was encoded utf-8. Error is:

UnicodeDecodeError: 'utf8' codec can't decode bytes in position 1-2: invalid continuation byte

**Comment by vishnevskiy** [comment]
I have tried it on 2 Macs and 1 Ubuntu and it works fine. When I get home I will give it a shot on my Windows machine.

**Comment by czarathustra** [comment]
I have isolated the issue to instances where the pythonw GUI is utilized to run the program. If i run the program directly from the command prompt and send the output to a text file, there is no error.

**Comment by czarathustra** [comment]
Closing this. Workaround identified.
